# projects.conf
# format: [project-name]:[target-path]
# ใส่ # เพื่อ comment

# Miruway Projects
miruway-api:D:/git/Miruway/Miruway-Api
miruway-bordgame:D:/git/Miruway/Miruway-Bordgame
miruway-bordgame-coup:D:/git/Miruway/Miruway-Bordgame-Coup
miruway-landing-page:D:/git/Miruway/Miruway-Landing-Page
miruway-shop-web:D:/git/Miruway/Miruway-Shop-Web
miruway-tts-discord:D:/git/Miruway/Miruway-TTS-Discord

# Oligio Projects
oligio-dashboard:D:/git/Oligio/dashboard
oligio-api:D:/git/Oligio/api
oligio-ar:D:/git/Oligio/oligio-ar